"""Pydantic schemas for all ScoutAI data types (§5).

Import everything from scoutai.schemas for convenience:
    from scoutai.schemas import GraphState, CandidateState, ShortlistEntry, ...
"""

from scoutai.schemas.types import (
    AvailabilitySlot,
    BiasIndicator,
    BiasReport,
    CapabilityAssessment,
    CapabilityHypotheses,
    CandidateState,
    Confidence,
    EvidenceBuckets,
    EvidenceItem,
    GraphState,
    InterviewQuestion,
    JDRelevance,
    ModelRole,
    PendingConfirmation,
    Recommendation,
    RecruiterSummary,
    Relevance,
    RequiredSkill,
    RoleProfile,
    Rubric,
    RubricCriterion,
    ScoreEntry,
    ShortlistEntry,
    TrajectoryEntry,
    TrajectoryStatus,
    UpdatedScoreCard,
    VerificationResult,
    VerificationVerdict,
    QuestionSet,
)

__all__ = [
    "AvailabilitySlot",
    "BiasIndicator",
    "BiasReport",
    "CapabilityAssessment",
    "CapabilityHypotheses",
    "CandidateState",
    "Confidence",
    "EvidenceBuckets",
    "EvidenceItem",
    "GraphState",
    "InterviewQuestion",
    "JDRelevance",
    "ModelRole",
    "PendingConfirmation",
    "Recommendation",
    "RecruiterSummary",
    "Relevance",
    "RequiredSkill",
    "RoleProfile",
    "Rubric",
    "RubricCriterion",
    "ScoreEntry",
    "ShortlistEntry",
    "TrajectoryEntry",
    "TrajectoryStatus",
    "UpdatedScoreCard",
    "VerificationResult",
    "VerificationVerdict",
    "QuestionSet",
]
